<?php

function sum_menu()
{
    $items = array();
    $items['sum'] = array(
        'title' => 'Calculate Sum',
        'type' => MENU_NORMAL_ITEM,
        'access callback' => TRUE,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('sum_form'),
      );
    $items['success'] = array(
      'title' => 'Suceess',
      'type' => MENU_CALLBACK,
      'page callback' => 'sum_success',
      'access callback' => TRUE,
      );
    return $items;
}

function sum_form()
{
    $form = array();
    $form['left_number'] = array(
          '#title' => 'left number',
          '#type' => 'textfield',
          '#description' => t('Please enter your number.'),
      );
    $form['right_number'] = array(
          '#title' => 'right number',
          '#type' => 'textfield',
          '#description' => t('Please enter a number to add'),
      );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Calculate Sum',
      );
    return $form;
}

function sum_form_submit($form, &$form_state)
{
    $first_number = $form_state['values']['left_number'];
    $second_number = $form_state['values']['right_number'];
    $sum = $first_number + $second_number;
    $_SESSION['sum_output'] = $sum;
    $form_state['redirect'] = 'success';
}

function sum_success()
{
    $answer = $_SESSION['sum_output'];
    return "You calculated a sum! The answer is $answer";
}
