<?php

function specials_menu()
{
    $items = array();
    $items['specials'] = array(
          'title' => 'specials',
          'page callback' => 'specials_display',
          'access callback' => TRUE,
          'type' => MENU_NORMAL_ITEM,

      );

    return $items;
}

function specials_display()
{
  return '
    <ul>
      <li>Latte</li>
      <li>Bacon</li>
      <li>Apples</li>
    </ul>
  ';
}
